### ISSUE TITLE
Packaging: Create RtAudioStreamer.AppImage

### ISSUE THREAD

**Issue by mxklb** [mxklb/rtaudiostreamer#9]
For common linux deployments there shall be an .AppImage

**Comment by mxklb** [comment]
AppImage is created and available as deployment artifact within GitLab (linked in README):

https://gitlab.com/mxklb/rtaudiostreamer/builds/artifacts/master/download?job=deploy_appimage

**Comment by probonopd** [comment]
Getting

> 403
> You don't have the permission to access this page. 

I am looking for a permalink to the AppImage.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1119

**Comment by mxklb** [comment]
Thank you for your interest, the link is corrected in the README, it changed to:

https://gitlab.com/mxklb/rtaudiostreamer/builds/artifacts/master/download?job=deploy_appimage

The link maybe is not public, I'll comme back to you as soon as I've got this fixed ..

**Comment by probonopd** [comment]
Getting error 403, access denied.

**Comment by mxklb** [comment]
Hmm, permissons page in gitlab says it's public .. but I'll get the same error when logged out :(

**Comment by mxklb** [comment]
I had to make the gitlab pipelines public, so now latest continuous version can be found at:

https://gitlab.com/mxklb/rtaudiostreamer/builds/artifacts/master/download?job=appimage_latest

Note: Gitlab build pipeline was improved, so the artifact contains .AppImage.zsync file
